### ISSUE TITLE
How much do you enlarge each proposal box?

### ISSUE THREAD

**Issue by tianweiy** [TuSimple/LiDAR_RCNN#1]
In the paper, "we enlarge its width and length to contain more contextual points around it". I wonder how much do you enlarge the box?

**Comment by tianweiy** [comment]
nvm, I found the answer

**Comment by happynear** [comment]
We enlarge the width and length by 3m, which means forward, backward, left, right borders are extended by 1.5m.

**Comment by tianweiy** [comment]
@happynear Thanks! One more question is the boundary offset to the enlarged box or the original proposal box ?

**Comment by happynear** [comment]
@tianweiy The original proposal bbox.

**Comment by tianweiy** [comment]
Good works! Thanks
