### ISSUE TITLE
How is the PP model trained

### ISSUE THREAD

**Issue by haotian-liu** [TuSimple/LiDAR_RCNN#11]
This model file `checkpoints/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth` in the docs cannot be found in mmdet3d official repo (they only have the interval-5 pretrained models). Are the proposals extracted with `interval-1` models: [3d-car](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car.py) and [3d-3class](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-3class.py)? If I want to reproduce your results, do I need to first train with these two configs? Thanks.

**Comment by Lzc6996** [comment]
@haotian-liu 
1. yes we use `interval-1` models
2. Please send me an email for this.  Due to license agreement of the waymo dataset, we can't make it public. Or you can just train models using mmdet3d.

**Comment by haotian-liu** [comment]
Thanks!

**Comment by Willforcv** [comment]
> @haotian-liu
> 
> 1. yes we use `interval-1` models
> 2. Please send me an email for this.  Due to license agreement of the waymo dataset, we can't make it public. Or you can just train models using mmdet3d.

Could you send me the relevant model？ hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth  and checkpoint_lidar_rcnn_59.pth.tar, thanks

**Comment by Lzc6996** [comment]
@Willforcv 
Please send me an email for this

**Comment by Willforcv** [comment]
***@***.***

thanks~
________________________________
发件人: Zhichao Li ***@***.***>
发送时间: 2021年7月6日 9:30
收件人: TuSimple/LiDAR_RCNN ***@***.***>
抄送: Willforcv ***@***.***>; Mention ***@***.***>
主题: Re: [TuSimple/LiDAR_RCNN] How is the PP model trained (#11)


@Willforcv<https://github.com/Willforcv>
Please send me an email for this

―

**Comment by Willforcv** [comment]
> @Willforcv
> Please send me an email for this



> @Willforcv
> Please send me an email for this


ghw8699536@hotmail.com

**Comment by Willforcv** [comment]
> @Willforcv
> Please send me an email for this

ghw8699536@hotmail.com

**Comment by Willforcv** [comment]
> @Willforcv
> Please send me an email for this

thanks~

**Comment by swwwu** [comment]
@Lzc6996  Hello, author of LiDAR R-CNN.   I'm trying to reproduce your work and I would like to use it after my detection network.  I have the same problem that could not find the trained models.  Could you please send me the models. ( hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar.)   

My email :  shwuuzh@hotmail.com

Thanks a lot.

**Comment by WangZZJJ** [comment]
Can you send me the checkpoint_lidar_rcnn_59.pth.tar ?
My email is  wangzijun@ime.ac.cn 
Thanks a lot.

**Comment by meanmee** [comment]
Can you send me the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar. ?
My email is wxmalan@163.com
Thanks a lot.

**Comment by jingjingliu-zju** [comment]
Can you send me the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar. ?
My email is m18627293699@163.com
Thanks a lot.

**Comment by Zhangyongtao123** [comment]
Can you send me the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar. ?
My email is zhangyongtao6666@gmail.com
Thanks a lot.

**Comment by Zhangyongtao123** [comment]
> @Willforcv Please send me an email for this
Hello! Did you get the models(hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar)? If so, please send me a copy of them.
My email is zhangyongtao6666@gmail.com. Thanks a lot.

**Comment by Zhangyongtao123** [comment]
> Thanks!

Hello! Did you get the models(hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar)? If so, please send me a copy of them.
My email is zhangyongtao6666@gmail.com. Thanks a lot.

**Comment by Lzc6996** [comment]
Thanks for your interest. I have sent the checkpoints to all of you.
I have released the multi-frame training code for LiDAR-RCNN, which leads to AP(L1) 77.8 based on PointPillars' proposals. You can try it anyway. Please feel free to contact me for further discussions!

**Comment by GatsbyChen** [comment]
Can you send me the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar. ?
My email is [18842647783@163.com](mailto:18842647783@163.com)
Thanks a lot.

**Comment by Lzc6996** [comment]
@GatsbyChen 
Done!

**Comment by neisakutou** [comment]
@Lzc6996 
Appreciate the team a lot for your fantastic work.
I am working on Lidar-RCNN facing the same issue mentioned above.
Could you please send me the pretrained model of 'checkpoints/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth'.
Email: ningzuotao@foxmail.com
Hope to hear from you soon.

**Comment by bruce-almon** [comment]
@Lzc6996
Thank you for sharing this work.
Can you send me the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar. ?
My email is skgre1600@gmail.com
Thanks a lot.

**Comment by fallfo** [comment]
@Lzc6996 
Thank you for sharing this work.
Could you send me the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar. ?
My email is [atri2549@163.com](atri2549@163.com)
Thanks a lot.

**Comment by kamalasubha** [comment]
@Lzc6996
Thank you for sharing this work.
Can you send me the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar. ?
My email is m.kamalasubha@gmail.com
Thanks in advance

**Comment by qingzhouzhen** [comment]
Thank you for sharing this work.
Can you send me the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar. ?
My email is 576591769@qq.com
Thanks a lot.

**Comment by zhouleidcc** [comment]
@Lzc6996
Thank you for your perfect work.
Hope you can send me the hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth and checkpoint_lidar_rcnn_59.pth.tar.
My email is [stoneswork@sina.com](url)
Thanks in advance
