### ISSUE TITLE
I have a question about " tx, ty, tz = (centers * pred_bbox[:, [3, 4, 5]]).T"

### ISSUE THREAD

**Issue by Suodislie** [TuSimple/LiDAR_RCNN#13]
def from_prediction_to_label_format(centers, sizes, headings,
                                    pred_bbox):
    l, w, h = (np.exp(sizes) * pred_bbox[:, [3, 4, 5]]).T
    ry = headings.reshape(-1)
    tx, ty, tz = (centers * pred_bbox[:, [3, 4, 5]]).T
    return l, w, h, tx, ty, tz, ry

**Comment by Lzc6996** [comment]
@Suodislie 
Please describe the problem in detail.

**Comment by Suodislie** [comment]
Shouldn't it be like this ：
tx, ty, tz = (centers * pred_bbox[:, [0，1，2]]).T ？

**Comment by Lzc6996** [comment]
@Lzc6996 
This function is the inverse of [parse_labels()](https://github.com/TuSimple/LiDAR_RCNN/blob/89c5fefd46563c15f31b8cda76e7ab09e2ddca0d/src/LiDAR_RCNN/utils/model_utils.py#L53)
