### ISSUE TITLE
Transfered To Nuscenes Dataset，Performance decline

### ISSUE THREAD

**Issue by Suodislie** [TuSimple/LiDAR_RCNN#14]
When I transfered it to the CenterpointNet and nuscenes datasets, Then evaluated on nuscense, it didn’t seem to work. I don’t know what went wrong, Looking forward to your suggestions and comments.

**Comment by Lzc6996** [comment]
The nuscenes dataset has a multi-frame setting becasue of the 20HZ 32L LiDAR. Do you add the delta time in input points?  @Suodislie

**Comment by Suodislie** [comment]
Thank you very much for your reminder, I just added a keyframe point cloud. Have you reproduced this idea in nuscense? In addition, what are the more important steps different from waymo, such as the selection of positive and negative samples, expand_proposal_meter parameters, etc.

**Comment by Lzc6996** [comment]
@Suodislie 
I haven't try it in nuscense. Maybe you should pay attention to positive and negative samples.

**Comment by Suodislie** [comment]
Ok. Ths for your suggestions ！

**Comment by Lzc6996** [comment]
@Suodislie If there are some new results in nuscenes please let me know. Feel free to contact me for further discussions!

**Comment by xxlbigbrother** [comment]
> 



> hallo！can you share the result of lidar-rcnn in nuscenes?  Performance decline  exactly?

**Comment by xxlbigbrother** [comment]
> Ok. Ths for your suggestions ！

hallo！can you share the result of lidar-rcnn in nuscenes? Performance decline exactly?

**Comment by hutao568** [comment]
@Lzc6996 hi~can you share your experiment on nuscenes?

**Comment by Lzc6996** [comment]
@hutao568 @xxlbigbrother 
Sorry, I didn't conduct a experiment on nuscenes.
For 10 frames point cloud as input，there are so many points not fall in the proposal box. Speed prediction can help us to find these points we need.  But I haven't do it on nuscenes dataset.

**Comment by qingzhouzhen** [comment]
Have figure out this problem? I trans this code to nuscnes on pointpillar, which lead to 10 percent decline, @Suodislie

**Comment by pmj110119** [comment]
> @hutao568 @xxlbigbrother Sorry, I didn't conduct a experiment on nuscenes. For 10 frames point cloud as input，there are so many points not fall in the proposal box. Speed prediction can help us to find these points we need. But I haven't do it on nuscenes dataset.

Will this algorithm perform worse in scenarios with more detailed categories (such as nuscenes)?

I'm not sure if you have tested on other data with more categories from waymo and kitti. Looking forward to your reply!
