### ISSUE TITLE
not find the pretrained model to extract proposal and checkpoints to test LiDarRcnn

### ISSUE THREAD

**Issue by Willforcv** [TuSimple/LiDAR_RCNN#15]
not find the pretrained model to extract proposal and checkpoints to test LiDarRcnn

**Comment by Willforcv** [comment]
checkpoint_lidar_rcnn_59.pth.tar  and hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth

**Comment by Lzc6996** [comment]
Duplicate of #11
