### ISSUE TITLE
Collaboration with MMDetection3D

### ISSUE THREAD

**Issue by ZwwWayne** [TuSimple/LiDAR_RCNN#2]
Hi developers of LiDAR R-CNN,

Congrats on the acceptance of the paper!

LiDAR R-CNN achieves new state-of-the-art results through simple yet effective improvement, which is very insightful to the community. We also found that the baseline is based on the implementations in [MMDetection3D](https://github.com/open-mmlab/mmdetection3d).

Therefore, I am coming to ask, as we believe LiDAR R-CNN might have a great impact on the community, would you like to also contribute an implementation of LiDAR R-CNN to  [MMDetection3D](https://github.com/open-mmlab/mmdetection3d)?
If so, maybe we could have a more detailed discussion about that?  MMDetection3D welcomes any kind of contribution. Please feel free to ask if there is anything from the MMDet3D team that could help.

On behalf of the MMDet3D Development Team

BR,

Wenwei

**Comment by happynear** [comment]
Hi Wenwei,

Thanks for the assistance when we built the baseline based on MMDetection3D. We are glad to contribute to the open source community. We are refactoring the codes and the codes will be released soon.
 
The algorithm is quite simple. I believe it is not difficult to transplant it to the MMDetection3D. However, the authors of this work are all full-time employees of TuSimple. We may not have enough time to make the codes compatible with MMDetection3D. Maybe your team would have some pioneers to do the work after our codes are released?

Thanks,
Feng Wang

**Comment by ZwwWayne** [comment]
OK great.

If so, we will keep update with you. Once your code is released, our team will help to migrate it to MMDet3D. Please feel free to review the PR if you have time or any comments. Your suggestions are valuable to us.

Cheers!

**Comment by yix081** [comment]
when will the code be released?

**Comment by happynear** [comment]
@ZwwWayne @yix081 Hi all, code has been released.

**Comment by wangkai602058765** [comment]
@happynear where can i find the code，thank you！

**Comment by DongfeiJi** [comment]
> Hi developers of LiDAR R-CNN,
> 
> Congrats on the acceptance of the paper!
> 
> LiDAR R-CNN achieves new state-of-the-art results through simple yet effective improvement, which is very insightful to the community. We also found that the baseline is based on the implementations in [MMDetection3D](https://github.com/open-mmlab/mmdetection3d).
> 
> Therefore, I am coming to ask, as we believe LiDAR R-CNN might have a great impact on the community, would you like to also contribute an implementation of LiDAR R-CNN to [MMDetection3D](https://github.com/open-mmlab/mmdetection3d)?
> If so, maybe we could have a more detailed discussion about that? MMDetection3D welcomes any kind of contribution. Please feel free to ask if there is anything from the MMDet3D team that could help.
> 
> On behalf of the MMDet3D Development Team
> 
> BR,
> 
> Wenwei

Has anyone added lidar-rcnn to mmdet3d?

**Comment by Lzc6996** [comment]
@DongfeiJi Not yet.
