### ISSUE TITLE
About tfrecord_parser.py

### ISSUE THREAD

**Issue by WangZZJJ** [TuSimple/LiDAR_RCNN#22]
Hello, I wonder what is the 'num_lidar_points_in_box'?  Do the waymo datasets has this key?

**Comment by Lzc6996** [comment]
@WangZZJJ 
Yes, it is. You can find it [here](https://github.com/waymo-research/waymo-open-dataset/blob/16c6a1a98fa8bb005fdfe798d27e6f3edf98c356/waymo_open_dataset/label.proto#L83). Actually,  WOD divides LEVEL_1 and LEVEL_2 depends on it.

**Comment by WangZZJJ** [comment]
Thanks for your reply.
