### ISSUE TITLE
About tfrecord_parser.py

### ISSUE THREAD

**Issue by WangZZJJ** [TuSimple/LiDAR_RCNN#24]
Hello, thanks for your work.
Why I run tfrecord_parser.py , but nothing occurred.
![nothing](https://user-images.githubusercontent.com/57397386/130941679-0017bc30-7adc-47fb-85aa-4effefb8f7c3.png)

**Comment by Lzc6996** [comment]
@WangZZJJ 
Can you  put the command you run here?
And I see the log "for raw pc 1 / 22", It's means it working for the first point cloud. Maybe you just need waiting.

**Comment by WangZZJJ** [comment]
> @WangZZJJ
> Can you put the command you run here?
> And I see the log "for raw pc 1 / 22", It's means it working for the first point cloud. Maybe you just need waiting.

Thanks for your reply! I know why the problem occur. But a new question, why it has AttributeError: num_lidar_points_in_box
![nu](https://user-images.githubusercontent.com/57397386/131277800-81cb232a-12f9-4c39-888b-c22d999ff214.png)

**Comment by Lzc6996** [comment]
@WangZZJJ 
You can find the  "num_lidar_points_in_box" [here](https://github.com/waymo-research/waymo-open-dataset/blob/16c6a1a98fa8bb005fdfe798d27e6f3edf98c356/waymo_open_dataset/label.proto#L83). Please check your datasets.
