### ISSUE TITLE
Tutorial link for data processor is dead

### ISSUE THREAD

**Issue by kamalasubha** [TuSimple/LiDAR_RCNN#31]
Hi,
Tutorial Link referred in the link https://github.com/tusen-ai/LiDAR_RCNN/blob/master/tools/data_processer/README.md is inactive
**Snapshot:**
![image](https://user-images.githubusercontent.com/36927102/184518608-1c32166f-96cb-46f7-9a6f-93dad1f7e464.png)
**Could you please give a document here for generating the dataset for testing?**

**Comment by Lzc6996** [comment]
@kamalasubha 
Thanks for pointing out the problem. I have fixed it. please try it again.
