### ISSUE TITLE
Link for tf records

### ISSUE THREAD

**Issue by kamalasubha** [TuSimple/LiDAR_RCNN#33]
Hi,
I am trying to generate data as mentioned in the data processor README. Can you please share the link to get tf records here? Whether it is referring to perception dataset v1.2 or tf records shared via mail?
![image](https://user-images.githubusercontent.com/36927102/188315738-0d8c40e1-cde5-4370-a7f2-22759727e783.png)

**Comment by Lzc6996** [comment]
@kamalasubha It means WOD perception dataset.

**Comment by kamalasubha** [comment]
@Lzc6996 Thanks. I will look into it
