### ISSUE TITLE
The pretrained model

### ISSUE THREAD

**Issue by SS-Yuan** [TuSimple/LiDAR_RCNN#34]
Hi, I am very interested in your paper, and I am reproducing it. The pretrained model of pointpillar provided in mmdetection3d does not reach the performance shown in the Table 2 below, so could you please provide the pretrained model of pointpillar in Table 2? Thank you very much!

![lidar_rcnn_per](https://user-images.githubusercontent.com/72961220/189105129-adc5c070-af86-410b-8b81-42e4a916b523.png)

**Comment by Lzc6996** [comment]
@SSY-1276 
Of cousre, can you give me your e-mail ?

**Comment by SS-Yuan** [comment]
Thank you for your reply. I'm SSY-1276 in github. My e-mail is ***@***.*** Thank you very much!
Best regards
















At 2022-09-09 09:50:15, "Zhichao Li" ***@***.***> wrote:

@SSY-1276
Of cousre, can you give me your e-mail ?

**Comment by Lzc6996** [comment]
@SSY-1276 
Pleasse check your msg, I can't get your e-mail.

**Comment by SS-Yuan** [comment]
My e-mail is yuan_shanshuai@163.com. Thank you

**Comment by SS-Yuan** [comment]
I reproduce lidar rcnn using your pretrained model. The mAP of vehicle has increased, but the mAP of pedestrain and cyclist each has 10-20 percentage points off. Have you met the problem like this? I have sent an e-mail to you describing this problem in detail.

**Comment by SS-Yuan** [comment]
![image](https://user-images.githubusercontent.com/72961220/189853331-4b6a7882-698a-422a-83f9-c092b2eb72da.png)
![image](https://user-images.githubusercontent.com/72961220/189853555-edb881f5-2faa-4abd-90c0-e2d9fe46e7c7.png)
I reproduce lidar rcnn using your pretrained model, but our results is not same as the results in the paper. Did you meet the question like this?
