### ISSUE TITLE
The pretrained model

### ISSUE THREAD

**Issue by hutao568** [TuSimple/LiDAR_RCNN#35]
hi~ Zhichao Li /Feng Wang/ Naiyan Wang~

我对你们的研究工作非常感兴趣，我在复现你们的工作，但是我没有hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth的模型去提取proposal；您可以提供我该预训练模型以及LiDAR R-CNN的模型吗？

(I am very interested in your research work, I am reproducing your work, but I do not have the model of hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth to extract the proposal; you can provide me with the pre-trained model and LiDAR R-CNN model?)

**Comment by hutao568** [comment]
我的email是hutao@buaa.edu.cn/771449987@qq.com

**Comment by Lzc6996** [comment]
@hutao568  plz check ur e-mail.

**Comment by hutao568** [comment]
Thank you very much for your quick response, I received this model.
