### ISSUE TITLE
Is ego pose information essential for using LiDAR R-CNN?

### ISSUE THREAD

**Issue by QingXIA233** [TuSimple/LiDAR_RCNN#38]
Hello, really impressive work! Currently, I've been working on using your model to refine CenterPoint-pp results with another dataset(not public ones). I notice that when performing transformation from point cloud points to proposals coordinate system, you use pose information like:
![image](https://user-images.githubusercontent.com/64100948/198545564-a25aec79-b7cc-4f64-a788-e365c64c3d8e.png)
However, the dataset I use has no precise pose information, but I think the proposals and the pc points of my model are already in the same coordinate system, thus I wonder in this case whether I could still use LiDAR R-CNN or I should resort to other second stage models. Could you provide me some advice? Thanks.

**Comment by Lzc6996** [comment]
@QingXIA233 
Hi, thanks for your interesting.
The ego motion is prepared for multi-frame setting. If you don't use multi-frame, it is not necessary.
You can see the version [v0.1.1](https://github.com/tusen-ai/LiDAR_RCNN/tree/v0.1.1) before the multi-frame version.
