### ISSUE TITLE
run python setup.py develop --user 报错。我的环境 cuda10.1 python3.6.2 pytorch1.6 ununtu16.04，请问该怎么解决？

### ISSUE THREAD

**Issue by ctgushiwei** [TuSimple/LiDAR_RCNN#4]

**Comment by Lzc6996** [comment]
Please show the details of the error messages @ctgushiwei

**Comment by ctgushiwei** [comment]
已经用邮件发送

**Comment by ctgushiwei** [comment]
![image](https://user-images.githubusercontent.com/11749965/119761773-05400c00-bedf-11eb-9d6a-fe6da6098b1d.png)

**Comment by Lzc6996** [comment]
@ctgushiwei 
please try `apt-get install ninja-build`

**Comment by ctgushiwei** [comment]
装好ninja-build和eigen后该问题已经解决

**Comment by ctgushiwei** [comment]
装好ninja-build和eigen后该问题已经解决
