### ISSUE TITLE
The cls scores are useless on my own dataset

### ISSUE THREAD

**Issue by xiuzhizheng** [TuSimple/LiDAR_RCNN#41]
Thanks for your awesome works. When I use Lidar-RCNN on my own dataset, the refine score is useless, Most objects are classified as backgrounds. In addition, the average refined center error is only reduced by 1 cm. I don't know Is this normal?

**Comment by Lzc6996** [comment]
@xiuzhizheng 
It looks like you give too much negtive samples in training set.

**Comment by xiuzhizheng** [comment]
> @xiuzhizheng It looks like you give too much negtive samples in training set.
Thank you for your apply. The ratio of positive samples is about 0.35. What range should we control this ratio。
One more question, In post-processing (/src/LiDAR_RCNN/utils/eval_utils.py line 78-83), we iterate through each box and assign it a score for each category, But in general, we choose the category with the largest score. Is this a trick?

**Comment by Lzc6996** [comment]
@xiuzhizheng 
You ratio seems fine. 
Changing to the maximum score should not greatly affect the results.

**Comment by xiuzhizheng** [comment]
@Lzc6996 Have you measured the increase in center point error?

**Comment by Lzc6996** [comment]
@xiuzhizheng The Table 8 in our paper may help.

**Comment by xiuzhizheng** [comment]
thanks for your help.
