### ISSUE TITLE
will not iou config filter proposal which are correct?

### ISSUE THREAD

**Issue by qingzhouzhen** [TuSimple/LiDAR_RCNN#43]
I do greatly appreciate to your work, but I am comfused with the threshold of proposal during training, for example 
`IOU_THRESHOLD: [1, 0.7, 0.5, 1, 0.5]` in [https://github.com/tusen-ai/LiDAR_RCNN/blob/master/config/lidar_rcnn_all_cls.yaml](url), 
will not this filter proposals which are exactly ground truth but iou low than 0.5?

**Comment by Lzc6996** [comment]
@qingzhouzhen 
It is used in [relabel](https://github.com/tusen-ai/LiDAR_RCNN/blob/c693828a5ff2d65ab7293c84837df9e3f6a7786b/src/LiDAR_RCNN/datasets/waymo/data_utils.py#L86). In which, the proposals have iou lower than threshold will be assigned to nagtive.
