### ISSUE TITLE
about aos metric

### ISSUE THREAD

**Issue by CocoBoom** [TuSimple/LiDAR_RCNN#44]
thanks for your work！
I apply your work on KITTI dataset.  However, I found that “aos” metric in KITTI datasets performs bad.
In the paper, when the predicted orientation is flipped with 180°， the orientation target is set to be the minimum residual calculated by original orientation and flipped orientation. It doesn't seem to fix the 180° flip orientation error. 
[In this function](https://github.com/tusen-ai/LiDAR_RCNN/blob/master/src/LiDAR_RCNN/datasets/waymo/loader.py#L71)

**Comment by Lzc6996** [comment]
@CocoBoom 
Yes, this func is used to fix the ambiguity of the heading loss, but it will not fix the 180 deg flip.
If you want to fix the it, you can add another loss, for example, a classification loss to judge if the heading is flip.

**Comment by zhangganv5** [comment]
> thanks for your work！ I apply your work on KITTI dataset. However, I found that “aos” metric in KITTI datasets performs bad. In the paper, when the predicted orientation is flipped with 180°， the orientation target is set to be the minimum residual calculated by original orientation and flipped orientation. It doesn't seem to fix the 180° flip orientation error. [In this function](https://github.com/tusen-ai/LiDAR_RCNN/blob/master/src/LiDAR_RCNN/datasets/waymo/loader.py#L71)

cloud you tell me how to reply it on kitti? THANKS！

**Comment by CocoBoom** [comment]
@zhangganv5 I've been on this project for ages, and lost track of the details. Sorry I couldn't be more help.
