### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by WOHJYY** [TuSimple/LiDAR_RCNN#46]
Hi, I am very interested in your paper, and I am reproducing it. Could you please provide the pretrained model of pointpillar in mmdet3d? Thank you very much!

**Comment by Lzc6996** [comment]
@WOHJYY 
Thank you for your attention. I need your email address.

**Comment by WOHJYY** [comment]
281341813@qq.com  Thanks very much!

> @WOHJYY Thank you for your attention. I need your email address.

**Comment by Lzc6996** [comment]
@WOHJYY 
please check your email.

**Comment by xueyingliu** [comment]
@Lzc6996 Hi，I am conducting some experiments related to your project. Could you please provide me the pretrained model mentioned above? My email is  1300684011@qq.com. Thank you so much~
