### ISSUE TITLE
The pretrained model

### ISSUE THREAD

**Issue by mobaixin** [TuSimple/LiDAR_RCNN#47]
Hello, I am very interested in your paper, and I am reproducing it. Could you please provide the pretrained model of Table 5. It's about 3D AP results on WOD with three classes trained in one model. My email is 13687162414@163.com. Thank you very much.
![1687186876100](https://github.com/tusen-ai/LiDAR_RCNN/assets/32213163/218199f3-2c47-4a42-9c0b-f0c371cb65d3)

**Comment by Lzc6996** [comment]
@mobaixin 
Thanks for your interest. 
I sorry for that we didn't keep the three classes model. I can send you the vehicle class model if you need it.

**Comment by mobaixin** [comment]
@Lzc6996 
Thanks for your reply.
That will be helpful. I need the vehicle class model. Thank you very much again.

**Comment by mobaixin** [comment]
I have received your email, thank you very much for your help.

**Comment by xueyingliu** [comment]
@mobaixin Hi，Could you please send me the pretrained model mentioned above? My email is [1300684011@qq.com](mailto:1300684011@qq.com). Thank you so much~
