### ISSUE TITLE
need your pretraind pth model

### ISSUE THREAD

**Issue by huang6886** [TuSimple/LiDAR_RCNN#48]
Hello, I am very interested in your paper, and I am now reproducing it. Could you please provide your  pretrained model with car, my email is huang6886@yeah.net, thank you very much

**Comment by Lzc6996** [comment]
plz, check your e-mail. @huang6886

**Comment by huang6886** [comment]
Thanks a lot , i have received your email.  Another request , do you still have the training/val set（.idx .rec）format( it seems a long time to handle the waymo dataset).

**Comment by Lzc6996** [comment]
I don't think the download will be much faster, but anyway, I sent it to you

**Comment by xueyingliu** [comment]
@huang6886 Hi，Could you please send me the pretrained model mentioned above? My email is [1300684011@qq.com](mailto:1300684011@qq.com). Thank you so much~

**Comment by Lzc6996** [comment]
@xueyingliu Hi, plz check your email, i have send it twice

**Comment by xueyingliu** [comment]
@Lzc6996 That’s very kind of you! I’ve received the email now.

**Comment by wayyeah** [comment]
@Lzc6996  Hi Could you please send me the pretrained model ? My email is 920258461@qq.com. Thank you so much~

**Comment by wayyeah** [comment]
> That’s very kind of you! I’ve received the email now.

@Lzc6996  That’s very kind of you! I’ve received the email now.
